const MOUSE_TYPE = {
    LEFT: 0,
    SCROLL: 1,
    RIGHT: 2,
}

const MOUSE_EVENT_NAME = {
    MOUSE_LEAVE: 'mouseleave',
}

const DIRECTION = {
    ALL: 'ALL',
    HORIZONTAL: 'HORIZONTAL',
    VERTICAL: 'VERTICAL',
}

const SCROLL_MODE = {
    NATIVE: 'NATIVE',
    TRANSFORM: 'TRANSFORM',
}

export { MOUSE_TYPE, MOUSE_EVENT_NAME, DIRECTION, SCROLL_MODE }
